version: '2'
services:
  kanboard:
    build:
      context: .
      args:
        VERSION: 1.0.37
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - kanboard_data:/var/www/app/data
     - ./plugins:/var/www/app/plugins
     - kanboard_ssl:/etc/nginx/ssl
volumes:
  kanboard_data:
    driver: local
  kanboard_ssl:
    driver: local
