name: Docker Image CI

on:
  push:
    branches:
      - master
      - 'v*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          

      - name: Build docker image
        #run: GIT_BRANCH=${GITHUB_REF##*/} make docker-build-images
        run: ./make docker-build-images

      #- name: Test docker image
      #  run: GIT_BRANCH=${GITHUB_REF##*/} make test

      - name: Push docker image for Debian
        run: GIT_BRANCH=${GITHUB_REF##*/} make docker-push

    
